pipeline {
    agent{
        docker{
            image 'python:2.7.16-slim'
        } 
    }

    stages {
        stage('build') {
            when{
                changeset "**/vote/**"
            }
            steps {
                echo 'Compile vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                } 
            }
        }
        stage('test') {
            when{
                changeset "**/vote/**"
            }
            steps {
                echo 'Running unit tests on vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }
    }

    post{
        always{
            echo "Pipeline for vote is complete.."
        }
        failure{
            echo "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }
        success{
            echo "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }
    }
}
