version: "3.7"

volumes:
  db-data: 
  redis-data:  

networks:
  instavote:
    driver: bridge

services:
  redis:
    image: redis:alpine
    networks:
      - instavote
    volumes:
      - "redis-data:/data"

  db:
    image: postgres:9.4
    networks:
      - instavote
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
        
  vote:
    image: xs98zprt/vote:master
    build: ./vote
    networks:
      - instavote
    ports:
      - 5000:80
    depends_on:
      - redis

  result:
    image: xs98zprt/result:master
    build: ./result
    networks:
      - instavote
    ports:
      - 5001:4000
    depends_on:
      - db

  worker:
    image: xs98zprt/worker:master
    build: ./worker
    networks:
      - instavote
    depends_on:
      - db
      - redis
